version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bff_search
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - 9229:9229
