version: '3.4'
services:
  front:
    image: node:latest
    container_name: front-end-nasa
    restart: always
    env_file:
      - .env
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm install
    command: npm start
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
